version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_API_DESPACHOS_URL=http://<IP_BACK_DESPACHOS>:8081
      - VITE_API_VENTAS_URL=http://<IP_BACK_VENTAS>:8088
